apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: 
          - /bin/sh
          - -c
          - echo Hello from the postStart handler > /usr/share/nginx/html/hook
      preStop:
        httpGet:
          path: hook
          port: 80
