apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
  - name: server
    image: nginx
    resources:
      requests:
        memory: "32Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
        cpu: "500m"
